### ISSUE TITLE
Different behaviour of 'no result found' message on schedule page and track page.

### ISSUE THREAD

**Issue by jainkeval** [fossasia/open-event-webapp#1729] opened 2018-02-26 13:17 UTC
**Actual Behaviour**

![giphy](https://user-images.githubusercontent.com/26284185/36672403-253d6de2-1b25-11e8-94e4-c2a0d3ba78aa.gif)

**Expected Behaviour**
The behaviour should be same on both pages.

**Comment by mariobehling** [comment] 2018-03-01 11:22
As far as i see the issue is that speaker names are not searched. Opened a dedicated issue that is more specific here: https://github.com/fossasia/open-event-webapp/issues/1734

Closing this one therefore. If there are more issues please try to be more narrow in the error and help to solve it. Thanks!

**Closed by mariobehling** 2018-03-01 11:22 UTC
