### ISSUE TITLE
UX: Stop website generation when zip is cancelled

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#952] opened 2017-01-06 16:13 UTC
The website generation does not stop even if the zip gets cancelled in between the generation process.

**Steps to reproduce the situation**

1. Upload the zip and hit generate app
2. Cancel the zip before the generation of the app is completed.

![ezgif com-gif-maker 1](https://cloud.githubusercontent.com/assets/12807846/21724106/ffc93ac8-d458-11e6-8f22-c74b5830222f.gif)

**Comment by geekyd** [comment] 2017-01-09 16:25
@aayusharora I have tried to solve the issue. please check the link and give your feedback.
https://open-event-web-appp.herokuapp.com/

**Comment by Princu7** [comment] 2017-01-09 18:40
@geekyd Looks great. Couple of points

* Please make the generation progress bar disappear on clicking the X button
* Clear up the existing logs.

**Comment by aayusharora** [comment] 2017-01-09 19:31
Looks good @Princu7 points seems valid in terms of UX. Better if we can achieve them with a transition .5 in hiding and showing the progress bar.

**Comment by geekyd** [comment] 2017-01-11 09:32
@Princu7 @aayusharora I have updated and added clearing the log feature.
But the progress does not stop as soon as the cancel but is clicked.

**Approach I have used**
- Created a variable in generator.js to maintain the status i.e if the user hits cancel or not
- Checked if the status is not false(cancel is not clicked) at start and end of each async.series function.

Can you please suggest if this is the correct approach?
Please give your feedback and suggest a solution.

**Comment by Princu7** [comment] 2017-01-11 11:53
@geekyd Thanks for the updates. I will look at the code and give feedback soon.

**Comment by geekyd** [comment] 2017-01-11 19:11
@Princu7 @aayusharora I suggest we should hide the generation progress bar if the upload gets cancelled and clear logs when the generation begins.
With hiding the bar we will stop the generation process as well this be a better user experience.

**Comment by aayusharora** [comment] 2017-01-11 19:24
@geekyd  Please take #946 also into consideration with your approaches. Both the issues will be solved by a single PR.

**Comment by geekyd** [comment] 2017-01-11 19:27
@aayusharora Yes it will solve both these issues with a single PR. Should I go ahead and implement the solution that i have suggested?

**Comment by Princu7** [comment] 2017-01-11 20:00
@geekyd Please hold on for a little while. I have reviewed your code. Excellent effort. Good work.  Some points

*  Be super careful while declaring global variables in the server-side code. Remeber, Nodejs is single threaded. All the connections execute on the same thread. You have made a variable 'appStatus' to maintain the status. By default, it is true and when you click on the X button, the value changes to false. You then check for it in each step of the generation process.

Now Imagine a scenario in which two users are generating a website around the same time. They both may be at different steps of the generation process. If one of them hits the X button, the appStatus will be changed to false. Since this is a global variable, the other user will also read the value of the appStatus as false and both the generation process would be terminated. 
I made a video demonstrating the problem
https://www.opentest.co/share/da23f7d0d83711e6a7cb6f2926412bab

* The reason why the progress doesn't stop immediately but continues for some time is due to the async steps written in the generator.js file. In a single async step we might be doing a lot of other works like copying uploads or transferring data. If we press the X button in the middle of a async step, there still might be a lot of work left before we move forward to the next async step. The additional statements that we see even after we hit the button are the log statements of these left works which we are still doing. Until we do these works, we won't proceed to the next step and until we proceed to the next step, we won't be able to stop the generation of buid logs.

* We will need to utilize the socket variable to solve this problem.

I am sorry if I was not able to clear things up. You can ping anytime you want :smiley:

**Comment by geekyd** [comment] 2017-01-11 20:22
Thank you for you feedback @Princu7 I'm solving all the issues you have mentioned, thank you for the helping out :)

**Comment by Princu7** [comment] 2017-01-11 20:29
@geekyd No problem at all. Keep up the great work :smile:

**Comment by geekyd** [comment] 2017-01-12 07:42
@Princu7 @aayusharora While addressing the issue I have noticed that the event queue places the cancel event at a later timestamp than the events triggered by the logger and the generator functions.

I have solved addressed this by placing the update percentage at 70% to the bottom , which made the cancel event to be placed before the emit callback at 70%. But the problem is the logger emit callbacks are placed before the click callback, which leads to logger sending the logs to the page after hitting cancel.

One solution is to place all the logger together.
Please suggest a solution.
You can reproduce the described problem by cancelling the generation before 70%.

Please check https://open-event-web-appp.herokuapp.com/

**Comment by Princu7** [comment] 2017-01-12 13:12
@geekyd This seems to be a typical problem where we are not able to find a perfect solution. Placing all logger statements together won't be a good thing to do. Also placing the update percentage below only solves a part of the problem and will break the structure of code.

I tried the app and it seems to just add a few statements after it has been canceled. That is very nice.Then I looked at the code and it seems like that _socket.status_ is used before all the logging statements. And when we have jumped out of the async steps due to the cancellation, we are explicitly deleting the whole logs again. That was something I was intending to tell. Instead of checking the status of the socket in the generator.js file again and again, we can do it inside the buildLogger.js file to the same effect!!

```
if(socket.status === true)
        socket.emit('buildLog', obj);

```
Now we need to work on some more things. The generation progress bar and the current message should immediately disappear on pressing the cancel button. It would also be nice if we could toggle the log button off at that time. That way the user won't be able to see the additional logs and we could clear up the additional logs quickly behind the scenes. This solution isn't perfect but looks quite good at the moment.

**Comment by geekyd** [comment] 2017-01-12 15:37
@Princu7 Excellent suggestion for checking the status, the code is messy coz I was trying to figure out how the events are placed in the queue. 
I was thinking the same we can simply toggle the logs and the progress bar and we clear the logs behind the scene, this way the user experience wont get hindered and we can provide a better experience for the user.
@aayusharora Please guide. Thank You!

**Comment by SparshBansal** [comment] 2017-02-19 01:05
@Princu7 , I deployed my version of the app at heroku without altering any code that cancels upload. Now when I cancel the file upload in the middle of the process , the logs show it is still being uploaded to server. I have created a PR where you can my changes to the code and also please look into the logs of the dev app running on heroku for the same bug.
My Version of the app : https://safe-sea-55983.herokuapp.com/

**Comment by Princu7** [comment] 2017-02-19 07:47
@SparshBansal Thanks for the request. Sorry, but I don't really understand you. :sweat_smile:  

> Now when I cancel the file upload in the middle of the process, the logs show it is still being uploaded to server

Which logs are you talking about? Yes, I tried out the test server and can see the stuck "Cancelling" text on the front end after canceling the file upload in the middle of the process. But on the back end, the file upload is canceled almost immediately. The lag on the front-end might be because of some issue in the code. You can try a zip of large size like OTS16 for greater clarity and cancel it and check the logs on the terminal. As soon as you press the X button, it is canceled almost immediately.

Here is a video demonstration for cancellation of upload
https://www.useloom.com/share/a81c8760f67411e6bca7777543759035

Link of the sample event(it is in unzipped version but you can make it a zip file when working locally)
https://github.com/fossasia/open-event/tree/master/sample/OTS16

I checked your PR but it's not much clear to me. Where are variables like `statusMap `defined?  They don't seem to exist in the official repository code. Please check it. Thanks!!

**Comment by Princu7** [comment] 2017-02-19 08:31
@SparshBansal @geekyd Was working earlier on the issue and had make a prototype. It would be great if you could both work together and discuss all the problems and solve the issue. It's a bit of a tricky issue and there are many edge cases to consider. It would also be good if you would read the previous discussions in this issue for greater understanding. Thanks!!!

**Comment by SparshBansal** [comment] 2017-02-19 10:16
@Princu7  I uploaded the development branch to heroku and recorded the video of the logs(Its in .ogv format, so please use ubuntu video app or vlc or something)

https://drive.google.com/open?id=0B1Hhi4gJoqW8X0xfelFTTEhHTUE

**Comment by Princu7** [comment] 2017-02-19 10:52
@SparshBansal Ok. It's weird. It's working locally but seems to be buggy on Heroku. Thank you so much for reporting :smile: Will surely look into it. Thanks!!

**Comment by SparshBansal** [comment] 2017-02-20 04:18
Demo Link : https://safe-sea-55983.herokuapp.com/
And like i said the upload cannot be cancelled on heroku because it doesn't fire the event until the upload completes on heroku.
@geekyd 
@Princu7 
@aayusharora

**Comment by Princu7** [comment] 2017-02-21 13:24
@SparshBansal @aayusharora @geekyd So I literally went scratching my hairs out of my head to find the cause of this error. The upload cancellation works on the localhost but doesn't seem to work on Heroku. The problem is a little hard to explain but I will try to give it a go.

The Socket-IO-file-upload library uses HTML5 FileReader API to upload the file in the browser buffer and uses socket events containing the chunks of data and emit them to the server. That's where the problem lies. As the data in the buffer is being filled up, socket events containing the chunk of data are transmitted to the server. Since the data fills up in the buffer really fast, a whole lot of socket events are created. Now since sending the data to the server(on Heroku) takes some time, whole lot of socket events are there in the process of transmission in the queue and the actual transmission of the socket events to server is slow.

Now suppose we press the Cancel button. A socket event is created. But it doesn't reach server immediately since there are already a lot of socket events which are in the process of transmitting. So the 'Cancel' event will be emitted only when the other data events have reached the server. So, our upload gets canceled real late. And in case, when we press the X button after the zip has been fully transferred in the buffer, then it is of no use since a whole lot of socket events containing all the data has been emitted and is in the process of transmitting is in the queue and our 'Cancel' event is behind all of them. So it will get to the server only after the whole zip file has been uploaded to the server.

So more late you will press X button, more late will the upload abort. Loosely, we can say that the percentage till which the file has been read up in the buffer when we cancel the X button, that much portion of the file will be transmitted to the server and then actual abort will take place. Network speed is the bottleneck here. If we could get a superfast network connection, then it will work. 

On localhost, the speed of filling up of data in the browser buffer and the data being sent to the server is **same** since it's the same computer. So, when we press the X button, the 'Cancel' event is emitted **almost** immediately and the upload gets canceled. Network is not the bottleneck here.

If we do it using another way without using FileReader API, it should maybe work. It seems that this job can't be done by socket-io-file-upload properly. We will have to search for some other options. I am currently looking at some other ways of doing this

**Comment by Princu7** [comment] 2017-02-21 13:32
@aayusharora @SparshBansal @geekyd I know this is hard to explain and understand. I have made some video demonstrations to clear the issue. 
The main point is the earlier we press the X button, less the data has been read in the browser buffer through the file reader API, so the lesser data will be transmitted to the server before our cancel event reaches and the upload is terminated. I made small changes in the code and you can see the effect of cancellation here
Cancellation done-

**Almost immediately**
https://www.useloom.com/share/d1e0d000f83711e69e969bd17f25a6e6

**After just a little delay**
https://www.useloom.com/share/e8fadaf0f83811e69e969bd17f25a6e6

**Comment by SparshBansal** [comment] 2017-02-21 13:41
There is this npm module called 'formidable' that i used for uploading binary data in my server. Please check it out and let me know if it is any good?

**Comment by Princu7** [comment] 2017-02-21 13:47
@SparshBansal I will check it out. Thanks :)

**Comment by aayusharora** [comment] 2017-02-21 18:51
@Princu7 @SparshBansal  I will go through the code later, when I get some time. But, what I can suggest after reading your explanation is we need a `change` event listener to check and cancel all uploads. 
Also if we use on this listener whenever `cancel ` is pressed  we can use  `instance.destroy`, it cancels all siofu work, that is going on. 
Please check with https://github.com/vote539/socketio-file-upload#instancedestroy

**Comment by Princu7** [comment] 2017-02-21 19:18
@aayusharora I tried doing it that way but it didn't seem to work properly.  `instance.destroy()` also destroys the `file upload input` element from the `DOM. `

I will try it again and see if it can be done this way. I am also looking at some other clean options which we can use which involve the use of streams. Will update you soon. Thanks :)

**Comment by geekyd** [comment] 2017-02-22 04:42
@Princu7 yes you got it right, I was facing the same issue while solving the issue, as soon as the user cancels the generation the event is emitted with a delay.

I will also check what other options we have for solving this issue.

**Comment by Princu7** [comment] 2017-03-03 19:37
@aayusharora The uploader.destroy() function is not able to stop the file being uploaded to the server. It continues to upload even after clicking the button. The events containing data have already been created and transmitted. So they continue to go to the server even after clicking the X button.

Link to the Video:
https://www.useloom.com/share/e9dfa1bcdb96477f94789fc6036c8ee

We will have to use some stream based library for uploading. I will look and present a working solution soon. Thanks!!

**Comment by geekyd** [comment] 2017-03-03 21:12
@Princu7 uploader.abort is a better option we can abort the upload and be done with it, it works for me check the video.

The upload gets aborted as soon as x is clicked, I have tried with several delays.
https://www.useloom.com/share/9d5e701a482b40feb5a6e06af61ae5dc

**Comment by Princu7** [comment] 2017-03-03 21:15
@geekyd It works on localhost but not on Heroku

**Comment by geekyd** [comment] 2017-03-03 21:27
@Princu7 Sorry. You are right the upload doesn't stop on Heroku.

**Comment by geekyd** [comment] 2017-03-04 07:31
@Princu7 @aayusharora Can we check the behavior on aws server?

**Comment by Princu7** [comment] 2017-03-04 07:38
@geekyd Yeah. We can test on the other servers. Actually, I initially thought that it was because of some error on Heroku but then I deployed the app on Digital Ocean and the error persisted. It is because of the socket-io-file-upload library. I have tried to explain the reason behind this in the earlier posts on this issue. Thanks :)

**Comment by Princu7** [comment] 2017-03-16 15:10
@aayusharora @geekyd So, I have almost completed the work on this issue. Like I said earlier, the problem was due to the `socket-io-file-upload library` which was using the `HTML5 FileReader API` for uploading of the files. This was causing problems and the downloads were continuing to being upload even after canceling.
We wanted some library which does the transfer using native `node streams` and provides `socket` support with it. I was searching and found an excellent library `socket.io-stream`. It is able for bidirectional data transfer between client and server using streams. We can track the progress of the upload of the server itself and it can be canceled easily. I will make a PR soon with the video demo :)

**Closed** 2017-04-25 10:46 UTC
Labels: bug, Hard
