### ISSUE TITLE
Make filter look better

### ISSUE THREAD

**Issue by shubham3211** [fossasia/open-event-webapp#1890] opened 2018-05-25 17:29 UTC
Improve the filter as on https://ossna2017.sched.com/
**Screenshots of the issue**

<!—-Where-ever possible add a screenshot of the issue.-—>
![filter](https://user-images.githubusercontent.com/19900978/40557893-4866e232-606f-11e8-9a56-b303859149e9.png)
**Would you like to work on the issue?**
Yes

**Comment by joeytwiddle** [comment] 2018-05-26 19:13
What is wrong with how it looks now? :innocent: Have you heard of any complaints or difficulties from users?

**Comment by shubham3211** [comment] 2018-05-26 21:35
@joeytwiddle No , but the one available on https://ossna2017.sched.com/ is better.

**Comment by agbilotia1998** [comment] 2018-06-04 15:18
Closing this, as the issue is fixed with #1893

**Closed by agbilotia1998** 2018-06-04 15:18 UTC
Labels: has-PR
