### ISSUE TITLE
Fix the broken eventyay icon

### ISSUE THREAD

**Issue by 0x48piraj** [fossasia/open-event-webapp#1629] opened 2018-01-09 15:05 UTC
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Broken **eventyay** icon in menu. (Also, in wrong dimensions. Should be in `48x48`)

**Expected behavior:**
Should display and can navigate to eventyay

---
**Screenshots of the issue:**

![image](https://user-images.githubusercontent.com/5800726/34727319-93f212b6-f57c-11e7-8c90-65f6b263a3f7.png)

**Comment by geekyd** [comment] 2018-01-23 09:18
The Issue is not valid as discussed in #1630 
Closing this.

**Closed by geekyd** 2018-01-23 09:18 UTC
Labels: has-PR
