### ISSUE TITLE
Links of the accounts of speakers on tracks page are not directing correctly as desired.

### ISSUE THREAD

**Issue by sumedh123** [fossasia/open-event-webapp#1225] opened 2017-04-20 06:07 UTC
**Actual behaviour**

![link](https://cloud.githubusercontent.com/assets/17925669/25215904/b9fcebf0-25bd-11e7-8991-a281aeedf3a4.gif)

**Expected**

The links should redirect to the correct pages.

**Comment by sumedh123** [comment] 2017-04-20 09:06
@aayusharora However, this problem is causing with only one speaker. Others are working fine. It might be due to the wrong data provided in json. Opinions?

**Comment by Abhi2424shek** [comment] 2017-04-20 09:09
Can you provide a value of the href of the link, I think it's because the link lacks HTTPS added to it.

**Comment by sumedh123** [comment] 2017-04-20 09:51
@Abhi2424shek No, it is not because of the lack of the protocol. See the gif. The link is appending i.e  'http://fossasia.github.io/open-event-webapp/www.github.com/AkshayTiwari'. While in other cases, it's correct.

**Comment by Princu7** [comment] 2017-04-21 12:26
Hi. Sorry for a late reply. Been quite busy due to the academics. Thanks for opening the issue. I guess @Abhi2424shek might be right.  I checked the actual JSON by searching on the http://eventyay.com/api/v1/events/6/speakers and it seems that the format of the links, in this case, is wrong when compared to the other speakers. For this particular speaker, the links are direct of the form `www.github.com/speaker-name` instead of `http://github.com/speaker-name` which might cause this problem. See the second answer in this StackOverflow thread http://stackoverflow.com/questions/8764288/href-automatically-adds-to-current-page-url-in-php-cant-figure-it-out
Please try to manually correct the URL to the correct format and see it the issue resolves. Thanks!

**Comment by sumedh123** [comment] 2017-04-21 14:22
@Princu7 Yeah I saw in developer tools that the href of the links are of the type "www.github.com/AkshayTiwari" instead of "https://github.com/AkshayTiwari". The json is incorrect then. Can we correct that json?

**Comment by Princu7** [comment] 2017-04-21 16:25
Yes. We can correct the JSON by opening an issue on the orga-server. The details of the speaker will have to be tweaked a little and I believe that the problem would be solved then. However, I am not really sure that it would be the best solution. We can try to handle these conditions on the client side instead of making changes on the server database. What do you say?

**Comment by sumedh123** [comment] 2017-04-21 17:28
@Princu7 According to me, we should leave it as it is since we are using the api endpoint for the test purpose only. I looked up into the speakers' json where I found that there is only one speaker with this issue. Everything is fine. Shall we keep it as it is for now? Since the JSONs for different events will be different, the data would be different.

**Comment by aayusharora** [comment] 2017-04-24 10:30
@sumedh123 For JSON specific issue, You can issue open here https://github.com/fossasia/open-event

**Comment by geekyd** [comment] 2017-04-24 19:53
The problem is for `FOSSASIA SUMMIT` api. I would suggest that we should add a check to make sure all links have a protocol if there is no protocol we will add it to the link. We can handle this in the generator itself.

**Comment by Princu7** [comment] 2017-08-10 18:42
Not related to webapp. Closing this :)

**Closed by Princu7** 2017-08-10 18:42 UTC
