### ISSUE TITLE
Unknown bug causes menu bar to disappear

### ISSUE THREAD

**Issue by 0x48piraj** [fossasia/open-event-webapp#1631] opened 2018-01-09 15:42 UTC
**Actual Behaviour**

**Unknown Bug** causes menu bar to disappear.

**Expected Behaviour**

Should be bug-free.

**Steps to reproduce it**

![openweb-app-gen-bug](https://user-images.githubusercontent.com/5800726/34729028-95aa2846-f581-11e7-8b7c-323b6aad1cec.gif)

**Log for the issue**

```
<div class="custom-menu-cont">
    <div class="custom-menu">
      <div class="hide-arrow"></div>
      <div class="custom-menu-cont">
        <div class="custom-menu-item">
          <a class="custom-icon" href="http://github.com/fossasia/open-event-webapp" target="_blank"><img src="./icons/code.png">
          <p class="custom-title">Code</p></a>
        </div>
        <div class="custom-menu-item">
          <a class="custom-icon" href="http://github.com/fossasia/open-event-webapp/issues" target="_blank"><img src="./icons/bug.png">
          <p class="custom-title">Bug Report</p></a>
        </div>
        <div class="custom-menu-item">
          <a class="custom-icon" href="http://blog.fossasia.org" target="_blank"><img src="./icons/blog.png">
          <p class="custom-title">Blogs</p></a>
        </div>
        <hr style="margin-bottom: 0; margin-top: 10px;">
        <div class="custom-menu-item">
          <a class="custom-icon" href="https://eventyay.com/" target="_blank"><img src="./icons/eventyay.png">
          <p class="custom-title">Eventyay</p></a>
        </div>
        <div class="custom-menu-item">
          <a class="custom-icon" href="https://susper.com/" target="_blank"><img src="./icons/susper.png">
          <p class="custom-title">Susper</p></a>
        </div>
        <div class="custom-menu-item">
          <a class="custom-icon" href="https://chat.susi.ai/" target="_blank"><img src="./icons/susi.png">
          <p class="custom-title">Susi</p></a>
        </div>
        <div class="custom-menu-item">
          <a class="custom-icon" href="https://fossasia.org/" target="_blank"><img src="./icons/fossasia.png">
          <p class="custom-title">FOSSASIA</p></a>
        </div>
        <div class="custom-menu-item">
          <a class="custom-icon" href="https://loklak.org/" target="_blank"><img src="./icons/loklak.png">
          <p class="custom-title">loklak</p></a>
        </div>
      </div>
    </div>
    <div class="custom-arrow"></div>
  </div>
```

**Would you like to work on the issue?**

Yes! *(Please don't send a PR without asking)*

**Comment by geekyd** [comment] 2018-01-10 09:11
@0x48piraj Nice one. Thanks for reporting this error. Please go ahead with this.

**Comment by tushargr** [comment] 2018-01-10 09:24
Hi I would really like to work on it. I looked at the code and could detect where the problem is.

**Comment by tushargr** [comment] 2018-01-10 13:13
Hi @geekyd @0x48piraj  could you please review my pull request. 
My deployment link- https://warm-headland-17924.herokuapp.com/
The menu bar button is now working correctly.

**Comment by 0x48piraj** [comment] 2018-01-10 14:39
The deployment link is not working @tushargr  and I want to work on this issue. I earlier said this :smile: 
I too have made progress, I added a javascript function that focuses on `email` text field. This resolves the bug.
We can do it together if you like.
Please share what approach you took ?
It will help in solving the bug in efficient and in collaborative manner.

**Comment by tushargr** [comment] 2018-01-10 14:50
Hey sorry earlier I took you as member of the organisation, so i started solving the issue.
I removed the earlier deployment, that's why it isn't working.

**Comment by 0x48piraj** [comment] 2018-01-10 14:55
Why you opened a Pull Request ?
I said I'm working and also completed it. :worried:

**Comment by 0x48piraj** [comment] 2018-01-10 14:58
Ping @geekyd 
It happens with me all the time. :sob: 
I said I'm working, and have completed it. I wanted to help him too so I asked him and he filed a PR.

**Comment by tushargr** [comment] 2018-01-10 15:00
I am really sorry ...as i told you i earlier took you as a member. The earlier PR had some problem so i submitted another. Please don't take it personally.

**Comment by vaibhavsingh97** [comment] 2018-01-10 16:30
@tushargr It's ok but @0x48piraj claimed it first so please close your PR. Thanks

**Comment by tushargr** [comment] 2018-01-10 17:50
@0x48piraj I am new to open source and this one is my first PR..i explained you about the misunderstanding. It will be really discouraging for me if i close the PR

**Comment by 0x48piraj** [comment] 2018-01-10 17:53
Do you know @tushargr , I have faced the same situation 8 times ? It's 9th !
Don't you think, It's too much ?

**Comment by 0x48piraj** [comment] 2018-01-10 17:55
We can do one thing though, I'll make my changes and you can make yours and we will submit the PR as one so that our contributions do not get wasted.

**Comment by geekyd** [comment] 2018-01-10 18:21
@0x48piraj There is no need to do a collaborative PR, the issue is fixed in #1638 . Have you already claimed the task for this? If not then I think we can merge #1638 .

@tushargr For future please leave a message asking if someone is already working on the issue or not. Please go through the guidelines https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/

**Comment by 0x48piraj** [comment] 2018-01-10 18:27
> Have you already claimed the task for this? If not then I think we can merge #1638 .

Yes @geekyd I have, and also for this case scenario, added a note.

Please tell him to close then.
I'll make the Pull Request. *(It will include a focus function too.)*

@vaibhavsingh97 knows, I always face this.

**Comment by geekyd** [comment] 2018-01-10 18:36
@0x48piraj I meant GCI Task. The PR has been closed. Please go ahead. :)

**Closed** 2018-01-12 08:07 UTC
Labels: has-PR
