### ISSUE TITLE
Facebook and G+ links broken.

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/open-event-webapp#1538] opened 2017-12-15 21:31 UTC
**Actual Behavior**

FB and G+ links on the login page ( http://open-event-dev.herokuapp.com/login/ ) are broken. 

**Expected Behavior**

When click those links it must be open correct way to login.
See in this link. Example for expected behavior - https://eventyay.com/login/
G+ link must be like this - 
https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=1033793180170-3hce8s4mcef7s878ojp4tbm9ijfh207i.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Feventyay.com%2FgCallback&scope=profile+email&state=6naN4K21FWqHPbLpfF5DuVX40cXP17&access_type=offline
FB link must be like this - 
https://www.facebook.com/dialog/oauth?response_type=code&client_id=203571866755829&redirect_uri=https%3A%2F%2Feventyay.com%2FfCallback&scope=public_profile+email&state=cI3tT3UWNZ4HIOQj93yWK1bcRJ9tt0&access_type=offline

**Steps to reproduce it**

Add correct links.

**Screen-shots of the issue**
Login page
![iss](https://user-images.githubusercontent.com/33794760/34061169-0552c4c4-e20d-11e7-8a95-156f2ae08cff.JPG)

Facebook link is broken.
![iss3](https://user-images.githubusercontent.com/33794760/34061188-175ad346-e20d-11e7-9ee7-273145ba6417.JPG)

G+ link is broken
![iss2](https://user-images.githubusercontent.com/33794760/34061201-286557c4-e20d-11e7-9fa7-b5b886dee8f0.JPG)

**Would you like to work on the issue?**
I am busy, Please work on this!

**Comment by shikhar-scs** [comment] 2017-12-17 15:28
The link for google + is working perfectly on the main site however the one for facebook is not.
@STEdirisuriya for anyone knowing the basics of authentication, it would be obvious that neither of them would work for herokuapp or any other similar deployment (unless the specific call back urls are set for it at console developers google).

The  problem needs to be addressed for facebook though.

**Comment by STEdirisuriya** [comment] 2017-12-18 20:55
http://open-event-dev.herokuapp.com/login/
no both are not working see this @shikhar-scs

**Comment by STEdirisuriya** [comment] 2017-12-18 20:59
Anyone work on this issue!

**Comment by ParthS007** [comment] 2017-12-18 21:06
You can go ahead @STEdirisuriya  👍

**Comment by shikhar-scs** [comment] 2017-12-19 02:08
I guess the problem is with some incorrect routing. I'd start working on it right away .

**Comment by shikhar-scs** [comment] 2017-12-19 05:30
@STEdirisuriya can you please provide me the source code for [https://eventyay.com/login/]( https://eventyay.com/login/) and [http://open-event-dev.herokuapp.com/login/](http://open-event-dev.herokuapp.com/login/) please. I need to work on them to fix this.

**Comment by geekyd** [comment] 2018-01-06 15:48
@STEdirisuriya This issue is for open-event-legacy repo. Please open an issue there if this still persists. Please check
https://github.com/fossasia/open-event-legacy

**Comment by shikhar-scs** [comment] 2018-01-06 15:51
Thanx @geekyd ... I'll check this out there

**Comment by abishekvashok** [comment] 2018-01-07 14:33
Can we close this pls?

**Closed** 2018-01-07 14:42 UTC
