### ISSUE TITLE
Sending Email links not working for Live Preview

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#991] opened 2017-01-15 17:06 UTC
## If the link is expired, Please show the info that it is expired.

**Comment by uttpal** [comment] 2017-01-17 08:29
@aayusharora For me its working fine. can you give steps to reproduce it?

**Comment by aayusharora** [comment] 2017-01-17 09:00
Hmm @uttpal  Strange! Can you verify for how many hours it remain active for you.

**Comment by meets2tarun** [comment] 2017-01-17 09:34
@aayusharora @uttpal  I too faced this problem. It doesn't send the email links.

**Comment by Princu7** [comment] 2017-01-17 09:57
@aayusharora @uttpal Sorry, I have been extremely unwell that's why not been active lately.
It is not a bug. Heroku doesn't offer persistent storage. It's erased after some time. That's why we had to upload the event folder to Amazon S3 so the user can access its generated event folder afterward.

Also, the uploaded event folders exist for only 3 days and then they are deleted automatically. I forgot to include that in the documentation. I will do it soon. Thank you.

**Comment by uttpal** [comment] 2017-01-17 10:12
@Princu7 Thanks for Information, I think it's fine the way it is as the user would download after it is generated, and we do not need to keep files too long.

**Comment by Princu7** [comment] 2017-01-17 10:19
@uttpal Yes. Actually, the 3 days deletion was added by me as stated by @mariobehling on the issue. It cleans up the older folders and there is no deduction of money from my debit card which might happen if the folders were not deleted regularly :smile:

**Comment by aayusharora** [comment] 2017-01-17 12:02
@Princu7 @uttpal  It seems that you misunderstood the issue, we know that this s3 storage will be clean out after 3 days. But, thinking from user perspective, it only shows Error page without much information.

**Comment by Princu7** [comment] 2017-01-17 12:46
@aayusharora Sorry. I guess that we can provide the info in the email itself that the live preview link will be cleared almost immediately and the s3 download link will be cleared in 3 days. Would love your suggestions.

**Comment by aayusharora** [comment] 2017-01-19 13:40
@uttpal There is already a 404 page made to handle errors.
 @Princu7 I think giving this information in mail itself can be best approach, so that the user is aware and download it before three days.

**Comment by Princu7** [comment] 2017-01-20 01:43
@aayusharora Agree. I will make necessary changes to the body of the email soon and make a request soon. Thanks!!

**Comment by aayusharora** [comment] 2017-02-21 17:48
@Princu7 Please update me with your progress.

**Comment by Princu7** [comment] 2017-02-21 19:33
@aayusharora I will send a PR tomorrow itself. Sorry for the delay.

**Comment by Princu7** [comment] 2017-03-11 14:26
This issue has been solved. Closing this :)

**Closed** 2017-03-11 14:29 UTC
Labels: bug
